const SEARCH_DATA = [
    // What's New
    { section: "What's New", title: "DuckDB", desc: "In-process SQL OLAP engine for Python", url: "https://duckdb.org/", tags: ["sql","duck","analytics","olap"] },
    { section: "What's New", title: "Polars", desc: "Fast DataFrame library written in Rust", url: "https://pola.rs/", tags: ["polars","dataframe","rust","python"] },
    { section: "What's New", title: "Marimo", desc: "Reactive Python notebook", url: "https://marimo.io/", tags: ["marimo","notebook","reactive","python"] },
    { section: "What's New", title: "uv Package Manager", desc: "Ultra-fast Python package manager in Rust", url: "https://docs.astral.sh/uv/", tags: ["uv","pip","python","tooling"] },
    { section: "What's New", title: "LeRobot", desc: "Hugging Face robot learning library", url: "https://github.com/huggingface/lerobot", tags: ["lerobot","robot","ml","huggingface"] },
    { section: "What's New", title: "Ruff", desc: "Fast Python linter and formatter", url: "https://docs.astral.sh/ruff/", tags: ["ruff","linter","formatter","python"] },
    // Python
    { section: "Python", title: "Real Python", desc: "Tutorials and articles for Python developers", url: "https://realpython.com/", tags: ["python","tutorial","library"] },
    { section: "Python", title: "Python Official Docs", desc: "Language reference docs.python.org", url: "https://docs.python.org/3/", tags: ["python","docs","reference"] },
    { section: "Python", title: "PyPI", desc: "Python Package Index â 500k packages", url: "https://pypi.org/", tags: ["python","packages","pip","libraries"] },
    { section: "Python", title: "MicroPython", desc: "Python on ESP32 and microcontrollers", url: "https://micropython.org/", tags: ["micropython","esp32","embedded","firmware"] },
    { section: "Python", title: "PySerial", desc: "Serial communication Python library", url: "https://pyserial.readthedocs.io/", tags: ["serial","arduino","uart","python"] },
    { section: "Python", title: "paho-mqtt", desc: "Python MQTT client library", url: "https://pypi.org/project/paho-mqtt/", tags: ["mqtt","iot","home assistant","python"] },
    { section: "Python", title: "LangChain", desc: "LLM app framework for Python", url: "https://python.langchain.com/", tags: ["langchain","llm","agents","ai","python"] },
    { section: "Python", title: "Ollama", desc: "Run local LLMs â Llama, Mistral, Phi", url: "https://ollama.com/", tags: ["ollama","llm","local","ai","python"] },
    { section: "Python", title: "Flask", desc: "Lightweight Python web framework", url: "https://flask.palletsprojects.com/", tags: ["flask","web","server","python"] },
    { section: "Python", title: "PythonAnywhere", desc: "Cloud Python hosting with scheduled tasks", url: "https://www.pythonanywhere.com/", tags: ["hosting","cloud","scheduled","python"] },
    { section: "Python", title: "watchdog", desc: "Filesystem event monitoring library", url: "https://pypi.org/project/watchdog/", tags: ["watchdog","filesystem","automation"] },
    { section: "Python", title: "JupyterLab", desc: "Interactive Python notebooks", url: "https://jupyter.org/", tags: ["jupyter","notebook","interactive","python"] },
    // Arduino
    { section: "Arduino", title: "Arduino Language Reference", desc: "Official Arduino function reference", url: "https://www.arduino.cc/reference/en/", tags: ["arduino","reference","official"] },
    { section: "Arduino", title: "Arduino Project Hub", desc: "Official curated project gallery", url: "https://projecthub.arduino.cc/", tags: ["arduino","projects","official"] },
    { section: "Arduino", title: "Wokwi Simulator", desc: "Browser-based Arduino and ESP32 simulator", url: "https://wokwi.com/", tags: ["wokwi","simulator","arduino","esp32","browser"] },
    { section: "Arduino", title: "PlatformIO", desc: "VS Code extension for embedded development", url: "https://platformio.org/", tags: ["platformio","vscode","ide","arduino","esp32"] },
    { section: "Arduino", title: "Adafruit Learning System", desc: "Free tutorials for Arduino and CircuitPython", url: "https://learn.adafruit.com/", tags: ["adafruit","arduino","tutorial","free"] },
    { section: "Arduino", title: "Last Minute Engineers", desc: "In-depth sensor and module tutorials", url: "https://lastminuteengineers.com/", tags: ["arduino","sensors","tutorials"] },
    { section: "Arduino", title: "FastLED", desc: "WS2812B LED strip library", url: "https://fastled.io/", tags: ["fastled","ws2812b","led","arduino"] },
    // ESP32
    { section: "ESP32", title: "Random Nerd Tutorials ESP32", desc: "Best ESP32 tutorial site", url: "https://randomnerdtutorials.com/projects-esp32/", tags: ["esp32","tutorial","wifi","mqtt","micropython"] },
    { section: "ESP32", title: "Espressif ESP-IDF Docs", desc: "Official ESP32 technical reference", url: "https://docs.espressif.com/projects/esp-idf/en/latest/", tags: ["esp32","esp-idf","espressif","official"] },
    { section: "ESP32", title: "ESPHome", desc: "YAML firmware for ESP32 Home Assistant integration", url: "https://esphome.io/", tags: ["esphome","home assistant","yaml","esp32","iot"] },
    { section: "ESP32", title: "WLED", desc: "WiFi LED control firmware for WS2812B", url: "https://kno.wled.ge/", tags: ["wled","led","ws2812b","esp32","wifi"] },
    { section: "ESP32", title: "Tasmota", desc: "Open-source firmware for smart home devices", url: "https://tasmota.github.io/docs/", tags: ["tasmota","smart home","mqtt","esp8266","esp32"] },
    // Robotics
    { section: "Robotics", title: "The Robotics Back-End", desc: "ROS 2, Python, Raspberry Pi robotics", url: "https://roboticsbackend.com/", tags: ["ros2","robotics","python","raspberry pi"] },
    { section: "Robotics", title: "ROS 2 Documentation", desc: "Official Robot Operating System 2 docs", url: "https://docs.ros.org/en/jazzy/", tags: ["ros2","robotics","official"] },
    { section: "Robotics", title: "LeRobot by Hugging Face", desc: "Robot learning library", url: "https://github.com/huggingface/lerobot", tags: ["lerobot","robot","ml","huggingface"] },
    { section: "Robotics", title: "PyBullet", desc: "Python physics simulation for robots", url: "https://pybullet.org/", tags: ["pybullet","simulation","physics","python"] },
    { section: "Robotics", title: "SunFounder PiCar-X", desc: "Robot car with Python SDK", url: "https://docs.sunfounder.com/projects/picar-x/en/latest/", tags: ["picar-x","sunfounder","raspberry pi","python"] },
    // Power Suite
    { section: "Power Suite", title: "DAX Guide", desc: "Complete DAX function reference", url: "https://dax.guide/", tags: ["dax","power bi","reference"] },
    { section: "Power Suite", title: "DAX Patterns", desc: "SQLBI DAX patterns library", url: "https://www.daxpatterns.com/", tags: ["dax","power bi","patterns","sqlbi"] },
    { section: "Power Suite", title: "Tabular Editor 2", desc: "Free Power BI model management tool", url: "https://tabulareditor.com/", tags: ["tabular editor","power bi","dax","free"] },
    { section: "Power Suite", title: "Guy in a Cube", desc: "Power BI YouTube channel", url: "https://www.youtube.com/@GuyInACube", tags: ["power bi","dax","youtube"] },
    { section: "Power Suite", title: "Copilot Studio", desc: "Build Microsoft Copilot agents", url: "https://learn.microsoft.com/en-us/microsoft-copilot-studio/", tags: ["copilot","studio","ai","microsoft"] },
    // Data Analytics
    { section: "Data Analytics", title: "DuckDB", desc: "In-process SQL analytics engine", url: "https://duckdb.org/", tags: ["duckdb","sql","analytics","python"] },
    { section: "Data Analytics", title: "Polars", desc: "Fast Rust-based DataFrame library", url: "https://pola.rs/", tags: ["polars","dataframe","python","rust"] },
    { section: "Data Analytics", title: "pandas", desc: "Standard Python DataFrame library", url: "https://pandas.pydata.org/docs/", tags: ["pandas","dataframe","python"] },
    { section: "Data Analytics", title: "Tableau Public", desc: "Free Tableau for data visualization", url: "https://public.tableau.com/", tags: ["tableau","visualization","free"] },
    { section: "Data Analytics", title: "DataLemur", desc: "SQL interview practice questions", url: "https://datalemur.com/", tags: ["sql","practice","interview","data"] },
    { section: "Data Analytics", title: "Kaggle", desc: "Datasets, competitions, and free courses", url: "https://www.kaggle.com/learn", tags: ["kaggle","dataset","python","sql","ml"] },
    { section: "Data Analytics", title: "WGU Student Portal", desc: "WGU BSDA program portal", url: "https://my.wgu.edu/", tags: ["wgu","bsda","data analytics","degree"] },
    // Excel
    { section: "Excel", title: "Leila Gharani", desc: "Modern Excel: LAMBDA, Power Query, dynamic arrays", url: "https://www.youtube.com/@LeilaGharani", tags: ["excel","lambda","power query","youtube"] },
    { section: "Excel", title: "ExcelIsFun", desc: "Mike Girvin's Excel tutorial archive", url: "https://www.youtube.com/@excelisfun", tags: ["excel","formulas","array","youtube"] },
    { section: "Excel", title: "Chandoo.org", desc: "Excel dashboards and tips", url: "https://chandoo.org/", tags: ["excel","dashboards","charts"] },
    // Python additions
    { section: "Python", title: "FastAPI", desc: "Build Python APIs fast â auto-docs, Pydantic types", url: "https://fastapi.tiangolo.com/", tags: ["python","api","fastapi","web"] },
    { section: "Python", title: "Pydantic", desc: "Data validation with Python type annotations", url: "https://docs.pydantic.dev/", tags: ["python","validation","types"] },
    { section: "Python", title: "SQLAlchemy", desc: "Python SQL toolkit and ORM", url: "https://docs.sqlalchemy.org/", tags: ["python","sql","orm","database"] },
    { section: "Python", title: "Python for Data Analysis", desc: "Wes McKinney's free pandas book", url: "https://wesmckinney.com/book/", tags: ["python","pandas","book","free"] },
    // Data Analytics additions
    { section: "Data Analytics", title: "StatQuest", desc: "Statistics and ML explained visually", url: "https://www.youtube.com/@statquest", tags: ["statistics","youtube","ml","wgu"] },
    { section: "Data Analytics", title: "Khan Academy Statistics", desc: "Free stats curriculum â hypothesis testing, regression", url: "https://www.khanacademy.org/math/statistics-probability", tags: ["statistics","free","beginner","wgu"] },
    { section: "Data Analytics", title: "Think Stats", desc: "Statistics for programmers in Python â free book", url: "https://greenteapress.com/thinkstats2/html/index.html", tags: ["statistics","python","book","free"] },
    { section: "Data Analytics", title: "Microsoft Fabric", desc: "Unified analytics platform â Lakehouse, Synapse, Power BI", url: "https://learn.microsoft.com/en-us/fabric/", tags: ["fabric","microsoft","data engineering","power bi"] },
    { section: "Data Analytics", title: "Guy in a Cube", desc: "Power BI and Fabric YouTube channel", url: "https://www.youtube.com/@GuyInACube", tags: ["power bi","fabric","youtube","dax"] },
    { section: "Data Analytics", title: "dbt", desc: "SQL-based data transformation for analytics engineering", url: "https://docs.getdbt.com/", tags: ["dbt","sql","transform","analytics engineering"] },
    { section: "Data Analytics", title: "Great Expectations", desc: "Data quality validation for Python pipelines", url: "https://greatexpectations.io/gx-oss", tags: ["data quality","python","pipeline"] },
    { section: "Data Analytics", title: "Metabase", desc: "Open source BI â dashboards without SQL", url: "https://www.metabase.com/", tags: ["bi","dashboards","open source"] },
    // Weekend additions
    { section: "Weekend", title: "Talk Python to Me", desc: "Python interviews and ecosystem news", url: "https://talkpython.fm/", tags: ["podcast","python","interviews"] },
    { section: "Weekend", title: "Python Bytes", desc: "Short-form Python news podcast", url: "https://pythonbytes.fm/", tags: ["podcast","python","news"] },
    { section: "Weekend", title: "Data Skeptic", desc: "Statistics, ML, and data science conversations", url: "https://dataskeptic.com/", tags: ["podcast","data","statistics","ml"] },
    { section: "Weekend", title: "Embedded.fm", desc: "Firmware, hardware, and embedded systems deep dives", url: "https://theembedded.fm/", tags: ["podcast","embedded","hardware"] },
    { section: "Weekend", title: "Corey Schafer Python", desc: "Python tutorials â OOP, decorators, pandas, Flask", url: "https://www.youtube.com/@coreyms", tags: ["python","tutorial","youtube"] },
    { section: "Weekend", title: "Keith Galli", desc: "Project-based pandas and data science tutorials", url: "https://www.youtube.com/@KeithGalli", tags: ["data science","pandas","youtube"] },
    { section: "Weekend", title: "WGU Student Portal", desc: "BSDA coursework and OA progress", url: "https://my.wgu.edu/", tags: ["wgu","bsda","coursework"] },
    // Raspberry Pi
    { section: "Raspberry Pi", title: "Raspberry Pi Official Docs", desc: "Setup, GPIO, hardware reference", url: "https://www.raspberrypi.com/documentation/", tags: ["raspberry pi","docs","gpio","official"] },
    { section: "Raspberry Pi", title: "MagPi Magazine", desc: "Free monthly PDF â projects and tutorials", url: "https://magpi.raspberrypi.com/", tags: ["raspberry pi","magazine","free","tutorials"] },
    { section: "Raspberry Pi", title: "Jeff Geerling", desc: "Pi benchmarks, NVMe, homelab builds", url: "https://www.youtube.com/@JeffGeerling", tags: ["raspberry pi","youtube","homelab","advanced"] },
    { section: "Raspberry Pi", title: "DietPi", desc: "Minimal OS for Pi Zero and single-board computers", url: "https://dietpi.com/", tags: ["raspberry pi","os","minimal","pi zero"] },
    // Home Automation
    { section: "Home Automation", title: "Home Assistant Docs", desc: "Official HA reference â integrations and automations", url: "https://www.home-assistant.io/docs/", tags: ["home assistant","smart home","automation","yaml"] },
    { section: "Home Automation", title: "HACS", desc: "Community store for custom HA integrations and cards", url: "https://hacs.xyz/", tags: ["home assistant","hacs","custom","lovelace"] },
    { section: "Home Automation", title: "ESPHome Components", desc: "YAML firmware config for ESP32 sensors", url: "https://esphome.io/components/", tags: ["esphome","esp32","yaml","sensors","home assistant"] },
    { section: "Home Automation", title: "Everything Smart Home", desc: "Home Assistant dashboards and automation YouTube", url: "https://www.youtube.com/@EverythingSmartHome", tags: ["home assistant","youtube","dashboards"] },
    // Homelab
    { section: "Homelab", title: "TechnoTim", desc: "Proxmox, Docker, networking homelab tutorials", url: "https://www.youtube.com/@TechnoTim", tags: ["homelab","docker","proxmox","youtube"] },
    { section: "Homelab", title: "NetworkChuck", desc: "Beginner networking, VLANs, Pi-hole, Docker", url: "https://www.youtube.com/@NetworkChuck", tags: ["homelab","networking","vlans","youtube","beginner"] },
    { section: "Homelab", title: "Pi-hole", desc: "Network-wide DNS ad blocking", url: "https://pi-hole.net/", tags: ["dns","ad blocking","pi-hole","privacy","networking"] },
    { section: "Homelab", title: "NGINX Proxy Manager", desc: "Reverse proxy with automatic SSL certificates", url: "https://nginxproxymanager.com/", tags: ["reverse proxy","ssl","nginx","homelab"] },
    { section: "Homelab", title: "Tailscale", desc: "Zero-config WireGuard VPN for homelab remote access", url: "https://tailscale.com/", tags: ["vpn","wireguard","remote access","homelab"] },
    { section: "Homelab", title: "Uptime Kuma", desc: "Self-hosted uptime monitoring with alerts", url: "https://github.com/louislam/uptime-kuma", tags: ["monitoring","uptime","self-hosted","docker"] },
    { section: "Homelab", title: "Portainer", desc: "Web UI for Docker container management", url: "https://www.portainer.io/", tags: ["docker","portainer","containers","web ui"] },
    { section: "Homelab", title: "Grafana", desc: "Open-source dashboards for metrics and monitoring", url: "https://grafana.com/", tags: ["grafana","dashboards","monitoring","metrics"] },
    { section: "Homelab", title: "Awesome Self-Hosted", desc: "Curated list of self-hosted application alternatives", url: "https://awesome-selfhosted.net/", tags: ["self-hosted","apps","directory","homelab"] },
    // Python expansions
    { section: "Python", title: "BeautifulSoup4", desc: "HTML/XML parsing for web scraping", url: "https://www.crummy.com/software/BeautifulSoup/bs4/doc/", tags: ["python","scraping","html","parsing"] },
    { section: "Python", title: "Playwright for Python", desc: "Browser automation for JavaScript-rendered pages", url: "https://playwright.dev/python/docs/intro", tags: ["python","automation","browser","scraping"] },
    { section: "Python", title: "Matplotlib", desc: "Foundational Python plotting library", url: "https://matplotlib.org/stable/tutorials/index.html", tags: ["python","charts","visualization","data"] },
    { section: "Python", title: "Seaborn", desc: "Statistical visualization built on Matplotlib", url: "https://seaborn.pydata.org/tutorial.html", tags: ["python","statistics","charts","visualization"] },
    { section: "Python", title: "Plotly", desc: "Interactive browser-based Python charts", url: "https://plotly.com/python/", tags: ["python","interactive","charts","jupyter"] },
    { section: "Python", title: "Streamlit", desc: "Turn Python scripts into shareable web apps", url: "https://streamlit.io/", tags: ["python","web app","dashboard","share"] },
    { section: "Python", title: "scikit-learn", desc: "Standard Python ML library â classification, regression, clustering", url: "https://scikit-learn.org/stable/user_guide.html", tags: ["python","machine learning","ml","bsda","classification"] },
    { section: "Python", title: "Kaggle Learn", desc: "Free Python, pandas, ML, and SQL micro-courses", url: "https://www.kaggle.com/learn", tags: ["python","free course","pandas","ml","datasets"] },
    { section: "Python", title: "Typer", desc: "Build CLI tools from Python functions using type hints", url: "https://typer.tiangolo.com/", tags: ["python","cli","tools","type hints"] },
    { section: "Python", title: "Rich", desc: "Beautiful terminal output â colors, tables, progress bars", url: "https://rich.readthedocs.io/", tags: ["python","terminal","cli","styling"] },
    { section: "Python", title: "pytest", desc: "The Python testing framework", url: "https://docs.pytest.org/en/stable/", tags: ["python","testing","pytest","quality"] },
    // Woodworking expansions
    { section: "Woodworking", title: "Ana White Free Plans", desc: "Thousands of free furniture woodworking plans", url: "https://www.ana-white.com/plans", tags: ["woodworking","free plans","furniture","cut list"] },
    { section: "Woodworking", title: "Wood Whisperer", desc: "Technique, tool selection, and joinery", url: "https://www.thewoodwhisperer.com/", tags: ["woodworking","technique","joinery","tools"] },
    { section: "Woodworking", title: "Woodworking for Mere Mortals", desc: "Free beginner weekend project plans", url: "https://www.woodworkingformeremortals.com/projects/", tags: ["woodworking","beginner","free plans","weekend"] },
    // Wearables
    { section: "ESP32", title: "Seeed XIAO ESP32-S3", desc: "Tiny ESP32-S3 module for wearable builds", url: "https://wiki.seeedstudio.com/xiao_esp32s3_getting_started/", tags: ["esp32","wearable","tiny","seeed"] },
    { section: "ESP32", title: "LilyGO T-Watch S3", desc: "DIY smartwatch with ESP32-S3", url: "https://github.com/Xinyuan-LilyGO/LILYGO-T-Watch-S3", tags: ["esp32","wearable","smartwatch","lilygo"] },
    { section: "ESP32", title: "CircuitPython", desc: "Beginner-friendly Python for 300+ boards", url: "https://circuitpython.org/", tags: ["circuitpython","adafruit","wearable","micropython"] },
    { section: "Excel", title: "The Spreadsheet Guru", desc: "Excel VBA, automation, and Power BI integration", url: "https://www.thespreadsheetguru.com/", tags: ["excel","vba","automation","power bi"] },
    // Woodworking
    { section: "Woodworking", title: "I Like to Make Stuff", desc: "Maker crossover: wood + electronics", url: "https://www.youtube.com/@iliketomakestuff", tags: ["woodworking","maker","electronics","youtube"] },
    { section: "Woodworking", title: "Steve Ramsey Woodworking", desc: "Beginner-friendly weekend projects", url: "https://www.youtube.com/@SteveRamsey", tags: ["woodworking","beginner","youtube"] },
    { section: "Woodworking", title: "Rogue Engineer", desc: "Free DIY plans, furniture, home improvement", url: "https://www.youtube.com/@rogueengineer", tags: ["woodworking","diy","free plans","youtube"] },
    { section: "Woodworking", title: "Fix This Build That", desc: "Brad Rodriguez â beginner to intermediate projects and tool reviews", url: "https://www.youtube.com/@Fixthisbuildthat", tags: ["woodworking","beginner","tool reviews","youtube"] },
    { section: "Woodworking", title: "Columbus Idea Foundry", desc: "Columbus makerspace with wood shop", url: "https://www.ideafoundry.com/", tags: ["makerspace","columbus","woodworking","tools"] },
    // News / Daily
    { section: "Daily", title: "Hackaday", desc: "Daily engineering hacks and news", url: "https://hackaday.com/", tags: ["hackaday","news","engineering","daily"] },
    { section: "Daily", title: "Hackster.io", desc: "Maker project community", url: "https://www.hackster.io/", tags: ["hackster","maker","projects","community"] },
    { section: "Daily", title: "CNX Software", desc: "New chip and embedded hardware news", url: "https://www.cnx-software.com/", tags: ["cnx","chips","hardware","news"] },
  ];